name: automerge
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: |
          exit 0
  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Merge
        run: |
          curl -sS -f -I -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/${{ vars.ORGANIZATION_VAR }}/${{ vars.REPOSITORY_VAR }}/pulls/${{ github.event.number }}/merge -v

