name: automerge
permissions:
  contents: write
on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run build script
        run: |
          exit 0
  automerge:
    needs: build
   runs-on: ubuntu-latest
    steps:
      - name: Merge
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_NUMBER: ${{ github.event.number }}
        run: |
          curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"  -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/Staatstrojaner/AnarchyTesting/pulls/${{ github.event.number }}/merge

